---
# tasks file for common
- name: upgrade all packages on the system [Archlinux]
  when: ansible_os_family == "Archlinux"
  pacman:
    upgrade: yes
    update_cache: yes

- name: add sublime text repository GPG key [Archlinux]
  when: ansible_os_family == "Archlinux"
  command: 'curl -O https://download.sublimetext.com/sublimehq-pub.gpg && pacman-key --add sublimehq-pub.gpg && pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg && echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | tee -a /etc/pacman.conf' 

- name: update package cache [Archlinux]
  when: ansible_os_family == "Archlinux"
  pacman:
    update_cache: yes

- name: install desired packages [Archlinux]
  when: ansible_os_family == "Archlinux"
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - terminator
      - gdb
      - ipcalc
      - sipcalc
      - asciinema
      - ncftp
      - zip
      - unzip
      - network-manager-openvpn
      - shellcheck
      - cowsay
      - sublime-text 
      - open-vm-tools
      - open-vm-tools-desktop
      - fuse
      - mlocate
      - cmake
      - python3
      - python3-pip
      - dh-autoreconf
      - ruby-full
      - git
      - compton
      - fonts-hack-ttf
      - rxvt-unicode
      - feh
      - i3-gaps
      - i3-wm
      - i3lock
      - i3status
      - dunst
      - suckless-tools
      - gdb
      - build-essentials
      - exuberant-ctags
      - numix-gtk-theme
      - rofi
      - zsh

- name: update locate database [Archlinux]
  when: ansible_os_family == "Archlinux"
  command: /usr/bin/updatedb
 
