---
# tasks file for common
- name: upgrade all packages on the system [Arch Linux]
  when: ansible_os_family == "Archlinux"
  pacman:
    upgrade: yes
    update_cache: yes

- name: add sublime text repository GPG key [Arch Linux]
  when: ansible_os_family == "Archlinux"
  shell: 'curl -O https://download.sublimetext.com/sublimehq-pub.gpg && pacman-key --add sublimehq-pub.gpg && pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg && echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | tee -a /etc/pacman.conf' 
  args:
    executable: /bin/bash
    warn: False

- name: update package cache [Arch Linux]
  when: ansible_os_family == "Archlinux"
  pacman:
    update_cache: yes

- name: install desired packages [Arch Linux]
  when: ansible_os_family == "Archlinux"
  pacman:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - terminator
      - gdb
      - ipcalc
      - sipcalc
      - asciinema
      - ncftp
      - zip
      - unzip
      - shellcheck
      - cowsay
      - sublime-text 
      - open-vm-tools
      - fuse
      - mlocate
      - cmake
      - python
      - python-pip
      - git
      - ruby
      - compton
      - rxvt-unicode
      - feh
      - i3-gaps
      - i3-wm
      - i3lock
      - i3status
      - dunst
      - ctags
      - numix-gtk-theme
      - rofi
      - zsh
      - xorg
      - xorg-xinit
      - wget
      - base-devel
      - zathura
      - zathura-pdf-poppler
      - vim
      - geany
      - gparted
      - htop
      - iotop
      - tree
      - ranger
      - lynx
      - ttf-dejavu
      - ttf-inconsolata
      - ttf-hack
      - lxappearance
      - arandr
      - ntfs-3g
      - udevil
      - alsa-firmware
      - alsa-utils
      - alsa-plugins
      - pulseaudio-alsa
      - pulseaudio

- name: update locate database [Arch Linux]
  when: ansible_os_family == "Archlinux"
  command: /usr/bin/updatedb
