---
# tasks file for common
- name: upgrade all packages on the system [Debian]
  when: ansible_os_family == "Debian"
  apt:
    name: "*"
    state: latest 
    update_cache: yes
    force_apt_get: yes

- name: add sublime text repository GPG key [Debian]
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present 

- name: add sublime text apt repository [Debian]
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: update package cache [Debian]
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    force_apt_get: yes

- name: install desired packages [Debian]
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
  vars:
    packages:
      - terminator
      - gdb
      - ipcalc
      - sipcalc
      - asciinema
      - ncftp
      - zip
      - unzip
      - network-manager-openvpn
      - shellcheck
      - cowsay
      - sublime-text 
      - open-vm-tools
      - open-vm-tools-desktop
      - fuse
      - mlocate
      - cmake
      - python3
      - python3-pip
      - dh-autoreconf
      - ruby-full
      - git
      - compton
      - fonts-hack-ttf
      - rxvt-unicode
      - feh
      - i3
      - i3-wm
      - i3lock
      - i3status
      - dunst
      - suckless-tools
      - libxcb-keysyms1-dev
      - libpango1.0-dev
      - libxcb-util0-dev
      - xcb
      - libxcb1-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libev-dev
      - libxcb-xkb-dev
      - libxcb-cursor-deb
      - libxkbcommon-dev
      - libxcb-xinerama0-dev
      - libxkbcommon-x11-dev
      - libstartup-notifications0-dev
      - libxcb-randr0-dev
      - libxcb-xrm0
      - libxcb-xrm-dev
      - gdb
      - build-essentials
      - exuberant-ctags
      - numix-gtk-theme
      - rofi

- name: remove dependencies that are no longer required [Debian]
  when: ansible_os_family == "Debian"
  apt:
    autoremove: yes
    force_apt_get: yes

- name: update locate database [Debian]
  when: ansible_os_family == "Debian"
  command: /usr/bin/updatedb
 
