---
# tasks file for common
- name: upgrade all packages on the system [Debian]
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: "*"
    state: latest 
    update_cache: yes
    force_apt_get: yes

- name: add sublime text repository GPG key [Debian]
  when: ansible_os_family == "Debian"
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present 

- name: add sublime text apt repository [Debian]
  when: ansible_os_family == "Debian"
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: update package cache [Debian]
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes

- name: install desired packages [Debian]
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
  vars:
    packages:
      - terminator
      - gdb
      - ipcalc
      - sipcalc
      - asciinema
      - ncftp
      - zip
      - unzip
      - network-manager-openvpn
      - shellcheck
      - cowsay
      - sublime-text 
      - open-vm-tools
      - open-vm-tools-desktop
      - fuse
      - mlocate
      - cmake
      - python3
      - python3-pip
      - dh-autoreconf
      - ruby-full
      - git
      - compton
      - fonts-hack-ttf
      - rxvt-unicode
      - feh
      - i3
      - i3-wm
      - i3lock
      - i3status
      - dunst
      - suckless-tools
      - gdb
      - exuberant-ctags
      - numix-gtk-theme
      - rofi
      - zsh
      - vim
      - tmux

- name: remove dependencies that are no longer required [Debian]
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    autoremove: yes
    force_apt_get: yes

- name: update locate database [Debian]
  when: ansible_os_family == "Debian"
  become: yes
  command: /usr/bin/updatedb
 
